# Generated by Django 5.1.5 on 2025-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_chapter_course_alter_chapter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='student_id',
        ),
    ]
